/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rubik.gltf --shadows 
*/


import React , {useEffect, useRef} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, OrthographicCamera } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Rubik(props) {
  const { scene } = useGLTF('/assets/model/rubik.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const meshGroupRef = useRef()

    useEffect(() => {
    meshGroupRef.current.children.forEach((item) => console.log(item.position))
    }, [props.item.body, props.mode])
  return (
    <group {...props} dispose={null}>
      <group scale={0.01} ref={meshGroupRef}>
        <directionalLight intensity={1} decay={2} rotation={[0, 0.48, 0]} target={nodes.Directional_Light.target}>
          <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
        </directionalLight>
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[-21.287, 375.86, 899.042]} rotation={[-0.385, -0.021, -0.008]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[23.015, 23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_2.geometry} material={nodes.cube_2.material} position={[13.885, 23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_3.geometry} material={nodes.cube_3.material} position={[23.015, 14.058, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_4.geometry} material={nodes.cube_4.material} position={[13.885, 14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_5.geometry} material={nodes.cube_5.material} position={[-13.883, 23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_6.geometry} material={nodes.cube_6.material} position={[-23.015, 23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_7.geometry} material={nodes.cube_7.material} position={[-13.883, 14.058, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_8.geometry} material={nodes.cube_8.material} position={[-23.013, 14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_9.geometry} material={nodes.cube_9.material} position={[4.565, 23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_10.geometry} material={nodes.cube_10.material} position={[-4.565, 23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_11.geometry} material={nodes.cube_11.material} position={[4.565, 14.058, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_12.geometry} material={nodes.cube_12.material} position={[-4.565, 14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_13.geometry} material={nodes.cube_13.material} position={[23.015, -14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_14.geometry} material={nodes.cube_14.material} position={[13.885, -14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_15.geometry} material={nodes.cube_15.material} position={[23.015, -23.187, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_16.geometry} material={nodes.cube_16.material} position={[13.885, -23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_17.geometry} material={nodes.cube_17.material} position={[-13.883, -14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_18.geometry} material={nodes.cube_18.material} position={[-23.015, -14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_19.geometry} material={nodes.cube_19.material} position={[-13.883, -23.187, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_20.geometry} material={nodes.cube_20.material} position={[-23.013, -23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_21.geometry} material={nodes.cube_21.material} position={[4.565, -14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_22.geometry} material={nodes.cube_22.material} position={[-4.565, -14.057, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_23.geometry} material={nodes.cube_23.material} position={[4.565, -23.187, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_24.geometry} material={nodes.cube_24.material} position={[-4.565, -23.188, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_25.geometry} material={nodes.cube_25.material} position={[23.015, 4.568, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_26.geometry} material={nodes.cube_26.material} position={[13.885, 4.568, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_27.geometry} material={nodes.cube_27.material} position={[23.015, -4.562, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_28.geometry} material={nodes.cube_28.material} position={[13.885, -4.563, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_29.geometry} material={nodes.cube_29.material} position={[-13.883, 4.568, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_30.geometry} material={nodes.cube_30.material} position={[-23.015, 4.568, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_31.geometry} material={nodes.cube_31.material} position={[-13.883, -4.562, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_32.geometry} material={nodes.cube_32.material} position={[-23.013, -4.563, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_33.geometry} material={nodes.cube_33.material} position={[4.565, 4.568, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_34.geometry} material={nodes.cube_34.material} position={[-4.565, 4.568, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_35.geometry} material={nodes.cube_35.material} position={[4.565, -4.562, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_36.geometry} material={nodes.cube_36.material} position={[-4.565, -4.563, -22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_37.geometry} material={nodes.cube_37.material} position={[23.015, 23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_38.geometry} material={nodes.cube_38.material} position={[13.885, 23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_39.geometry} material={nodes.cube_39.material} position={[23.015, 14.058, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_40.geometry} material={nodes.cube_40.material} position={[13.885, 14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_41.geometry} material={nodes.cube_41.material} position={[-13.883, 23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_42.geometry} material={nodes.cube_42.material} position={[-23.015, 23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_43.geometry} material={nodes.cube_43.material} position={[-13.883, 14.058, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_44.geometry} material={nodes.cube_44.material} position={[-23.013, 14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_45.geometry} material={nodes.cube_45.material} position={[4.565, 23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_46.geometry} material={nodes.cube_46.material} position={[-4.565, 23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_47.geometry} material={nodes.cube_47.material} position={[4.565, 14.058, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_48.geometry} material={nodes.cube_48.material} position={[-4.565, 14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_49.geometry} material={nodes.cube_49.material} position={[23.015, -14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_50.geometry} material={nodes.cube_50.material} position={[13.885, -14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_51.geometry} material={nodes.cube_51.material} position={[23.015, -23.187, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_52.geometry} material={nodes.cube_52.material} position={[13.885, -23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_53.geometry} material={nodes.cube_53.material} position={[-13.883, -14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_54.geometry} material={nodes.cube_54.material} position={[-23.015, -14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_55.geometry} material={nodes.cube_55.material} position={[-13.883, -23.187, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_56.geometry} material={nodes.cube_56.material} position={[-23.013, -23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_57.geometry} material={nodes.cube_57.material} position={[4.565, -14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_58.geometry} material={nodes.cube_58.material} position={[-4.565, -14.057, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_59.geometry} material={nodes.cube_59.material} position={[4.565, -23.187, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_60.geometry} material={nodes.cube_60.material} position={[-4.565, -23.188, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_61.geometry} material={nodes.cube_61.material} position={[23.015, 4.568, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_62.geometry} material={nodes.cube_62.material} position={[13.885, 4.568, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_63.geometry} material={nodes.cube_63.material} position={[23.015, -4.562, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_64.geometry} material={nodes.cube_64.material} position={[13.885, -4.563, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_65.geometry} material={nodes.cube_65.material} position={[-13.883, 4.568, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_66.geometry} material={nodes.cube_66.material} position={[-23.015, 4.568, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_67.geometry} material={nodes.cube_67.material} position={[-13.883, -4.562, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_68.geometry} material={nodes.cube_68.material} position={[-23.013, -4.563, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_69.geometry} material={nodes.cube_69.material} position={[4.565, 4.568, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_70.geometry} material={nodes.cube_70.material} position={[-4.565, 4.568, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_71.geometry} material={nodes.cube_71.material} position={[4.565, -4.562, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_72.geometry} material={nodes.cube_72.material} position={[-4.565, -4.563, -13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_73.geometry} material={nodes.cube_73.material} position={[23.015, 23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_74.geometry} material={nodes.cube_74.material} position={[13.885, 23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_75.geometry} material={nodes.cube_75.material} position={[23.015, 14.058, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_76.geometry} material={nodes.cube_76.material} position={[13.885, 14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_77.geometry} material={nodes.cube_77.material} position={[-13.883, 23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_78.geometry} material={nodes.cube_78.material} position={[-23.015, 23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_79.geometry} material={nodes.cube_79.material} position={[-13.883, 14.058, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_80.geometry} material={nodes.cube_80.material} position={[-23.013, 14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_81.geometry} material={nodes.cube_81.material} position={[4.565, 23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_82.geometry} material={nodes.cube_82.material} position={[-4.565, 23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_83.geometry} material={nodes.cube_83.material} position={[4.565, 14.058, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_84.geometry} material={nodes.cube_84.material} position={[-4.565, 14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_85.geometry} material={nodes.cube_85.material} position={[23.015, -14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_86.geometry} material={nodes.cube_86.material} position={[13.885, -14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_87.geometry} material={nodes.cube_87.material} position={[23.015, -23.187, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_88.geometry} material={nodes.cube_88.material} position={[13.885, -23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_89.geometry} material={nodes.cube_89.material} position={[-13.883, -14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_90.geometry} material={nodes.cube_90.material} position={[-23.015, -14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_91.geometry} material={nodes.cube_91.material} position={[-13.883, -23.187, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_92.geometry} material={nodes.cube_92.material} position={[-23.013, -23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_93.geometry} material={nodes.cube_93.material} position={[4.565, -14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_94.geometry} material={nodes.cube_94.material} position={[-4.565, -14.057, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_95.geometry} material={nodes.cube_95.material} position={[4.565, -23.187, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_96.geometry} material={nodes.cube_96.material} position={[-4.565, -23.188, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_97.geometry} material={nodes.cube_97.material} position={[23.015, 4.568, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_98.geometry} material={nodes.cube_98.material} position={[13.885, 4.568, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_99.geometry} material={nodes.cube_99.material} position={[23.015, -4.562, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_100.geometry} material={nodes.cube_100.material} position={[13.885, -4.563, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_101.geometry} material={nodes.cube_101.material} position={[-13.883, 4.568, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_102.geometry} material={nodes.cube_102.material} position={[-23.015, 4.568, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_103.geometry} material={nodes.cube_103.material} position={[-13.883, -4.562, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_104.geometry} material={nodes.cube_104.material} position={[-23.013, -4.563, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_105.geometry} material={nodes.cube_105.material} position={[4.565, 4.568, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_106.geometry} material={nodes.cube_106.material} position={[-4.565, 4.568, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_107.geometry} material={nodes.cube_107.material} position={[4.565, -4.562, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_108.geometry} material={nodes.cube_108.material} position={[-4.565, -4.563, -4.587]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_109.geometry} material={nodes.cube_109.material} position={[23.015, 23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_110.geometry} material={nodes.cube_110.material} position={[13.885, 23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_111.geometry} material={nodes.cube_111.material} position={[23.015, 14.058, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_112.geometry} material={nodes.cube_112.material} position={[13.885, 14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_113.geometry} material={nodes.cube_113.material} position={[-13.883, 23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_114.geometry} material={nodes.cube_114.material} position={[-23.015, 23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_115.geometry} material={nodes.cube_115.material} position={[-13.883, 14.058, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_116.geometry} material={nodes.cube_116.material} position={[-23.013, 14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_117.geometry} material={nodes.cube_117.material} position={[4.565, 23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_118.geometry} material={nodes.cube_118.material} position={[-4.565, 23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_119.geometry} material={nodes.cube_119.material} position={[4.565, 14.058, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_120.geometry} material={nodes.cube_120.material} position={[-4.565, 14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_121.geometry} material={nodes.cube_121.material} position={[23.015, -14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_122.geometry} material={nodes.cube_122.material} position={[13.885, -14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_123.geometry} material={nodes.cube_123.material} position={[23.015, -23.187, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_124.geometry} material={nodes.cube_124.material} position={[13.885, -23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_125.geometry} material={nodes.cube_125.material} position={[-13.883, -14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_126.geometry} material={nodes.cube_126.material} position={[-23.015, -14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_127.geometry} material={nodes.cube_127.material} position={[-13.883, -23.187, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_128.geometry} material={nodes.cube_128.material} position={[-23.013, -23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_129.geometry} material={nodes.cube_129.material} position={[4.565, -14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_130.geometry} material={nodes.cube_130.material} position={[-4.565, -14.057, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_131.geometry} material={nodes.cube_131.material} position={[4.565, -23.187, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_132.geometry} material={nodes.cube_132.material} position={[-4.565, -23.188, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_133.geometry} material={nodes.cube_133.material} position={[23.015, 4.568, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_134.geometry} material={nodes.cube_134.material} position={[13.885, 4.568, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_135.geometry} material={nodes.cube_135.material} position={[23.015, -4.562, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_136.geometry} material={nodes.cube_136.material} position={[13.885, -4.563, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_137.geometry} material={nodes.cube_137.material} position={[-13.883, 4.568, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_138.geometry} material={nodes.cube_138.material} position={[-23.015, 4.568, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_139.geometry} material={nodes.cube_139.material} position={[-13.883, -4.562, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_140.geometry} material={nodes.cube_140.material} position={[-23.013, -4.563, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_141.geometry} material={nodes.cube_141.material} position={[4.565, 4.568, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_142.geometry} material={nodes.cube_142.material} position={[-4.565, 4.568, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_143.geometry} material={nodes.cube_143.material} position={[4.565, -4.562, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_144.geometry} material={nodes.cube_144.material} position={[-4.565, -4.563, 4.55]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_145.geometry} material={nodes.cube_145.material} position={[23.015, 23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_146.geometry} material={nodes.cube_146.material} position={[13.885, 23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_147.geometry} material={nodes.cube_147.material} position={[23.015, 14.058, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_148.geometry} material={nodes.cube_148.material} position={[13.885, 14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_149.geometry} material={nodes.cube_149.material} position={[-13.883, 23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_150.geometry} material={nodes.cube_150.material} position={[-23.015, 23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_151.geometry} material={nodes.cube_151.material} position={[-13.883, 14.058, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_152.geometry} material={nodes.cube_152.material} position={[-23.013, 14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_153.geometry} material={nodes.cube_153.material} position={[4.565, 23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_154.geometry} material={nodes.cube_154.material} position={[-4.565, 23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_155.geometry} material={nodes.cube_155.material} position={[4.565, 14.058, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_156.geometry} material={nodes.cube_156.material} position={[-4.565, 14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_157.geometry} material={nodes.cube_157.material} position={[23.015, -14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_158.geometry} material={nodes.cube_158.material} position={[13.885, -14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_159.geometry} material={nodes.cube_159.material} position={[23.015, -23.187, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_160.geometry} material={nodes.cube_160.material} position={[13.885, -23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_161.geometry} material={nodes.cube_161.material} position={[-13.883, -14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_162.geometry} material={nodes.cube_162.material} position={[-23.015, -14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_163.geometry} material={nodes.cube_163.material} position={[-13.883, -23.187, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_164.geometry} material={nodes.cube_164.material} position={[-23.013, -23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_165.geometry} material={nodes.cube_165.material} position={[4.565, -14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_166.geometry} material={nodes.cube_166.material} position={[-4.565, -14.057, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_167.geometry} material={nodes.cube_167.material} position={[4.565, -23.187, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_168.geometry} material={nodes.cube_168.material} position={[-4.565, -23.188, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_169.geometry} material={nodes.cube_169.material} position={[23.015, 4.568, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_170.geometry} material={nodes.cube_170.material} position={[13.885, 4.568, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_171.geometry} material={nodes.cube_171.material} position={[23.015, -4.562, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_172.geometry} material={nodes.cube_172.material} position={[13.885, -4.563, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_173.geometry} material={nodes.cube_173.material} position={[-13.883, 4.568, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_174.geometry} material={nodes.cube_174.material} position={[-23.015, 4.568, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_175.geometry} material={nodes.cube_175.material} position={[-13.883, -4.562, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_176.geometry} material={nodes.cube_176.material} position={[-23.013, -4.563, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_177.geometry} material={nodes.cube_177.material} position={[4.565, 4.568, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_178.geometry} material={nodes.cube_178.material} position={[-4.565, 4.568, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_179.geometry} material={nodes.cube_179.material} position={[4.565, -4.562, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_180.geometry} material={nodes.cube_180.material} position={[-4.565, -4.563, 13.855]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_181.geometry} material={nodes.cube_181.material} position={[23.015, 23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_182.geometry} material={nodes.cube_182.material} position={[13.885, 23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_183.geometry} material={nodes.cube_183.material} position={[23.015, 14.058, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_184.geometry} material={nodes.cube_184.material} position={[13.885, 14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_185.geometry} material={nodes.cube_185.material} position={[-13.883, 23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_186.geometry} material={nodes.cube_186.material} position={[-23.015, 23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_187.geometry} material={nodes.cube_187.material} position={[-13.883, 14.058, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_188.geometry} material={nodes.cube_188.material} position={[-23.013, 14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_189.geometry} material={nodes.cube_189.material} position={[4.565, 23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_190.geometry} material={nodes.cube_190.material} position={[-4.565, 23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_191.geometry} material={nodes.cube_191.material} position={[4.565, 14.058, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_192.geometry} material={nodes.cube_192.material} position={[-4.565, 14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_193.geometry} material={nodes.cube_193.material} position={[23.015, -14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_194.geometry} material={nodes.cube_194.material} position={[13.885, -14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_195.geometry} material={nodes.cube_195.material} position={[23.015, -23.187, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_196.geometry} material={nodes.cube_196.material} position={[13.885, -23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_197.geometry} material={nodes.cube_197.material} position={[-13.883, -14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_198.geometry} material={nodes.cube_198.material} position={[-23.015, -14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_199.geometry} material={nodes.cube_199.material} position={[-13.883, -23.187, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_200.geometry} material={nodes.cube_200.material} position={[-23.013, -23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_201.geometry} material={nodes.cube_201.material} position={[4.565, -14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_202.geometry} material={nodes.cube_202.material} position={[-4.565, -14.057, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_203.geometry} material={nodes.cube_203.material} position={[4.565, -23.187, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_204.geometry} material={nodes.cube_204.material} position={[-4.565, -23.188, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_205.geometry} material={nodes.cube_205.material} position={[23.015, 4.568, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_206.geometry} material={nodes.cube_206.material} position={[13.885, 4.568, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_207.geometry} material={nodes.cube_207.material} position={[23.015, -4.562, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_208.geometry} material={nodes.cube_208.material} position={[13.885, -4.563, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_209.geometry} material={nodes.cube_209.material} position={[-13.883, 4.568, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_210.geometry} material={nodes.cube_210.material} position={[-23.015, 4.568, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_211.geometry} material={nodes.cube_211.material} position={[-13.883, -4.562, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_212.geometry} material={nodes.cube_212.material} position={[-23.013, -4.563, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_213.geometry} material={nodes.cube_213.material} position={[4.565, 4.568, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_214.geometry} material={nodes.cube_214.material} position={[-4.565, 4.568, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_215.geometry} material={nodes.cube_215.material} position={[4.565, -4.562, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh castShadow receiveShadow geometry={nodes.cube_216.geometry} material={nodes.cube_216.material} position={[-4.565, -4.563, 22.992]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/model/rubik.gltf')
